### ISSUE TITLE
Recursive include replacement

### ISSUE THREAD

**Issue by albireox** [bitranox/rst_include#3]
* **I'm submitting a ... **
  - [ ] bug report
  - [X] feature request
  - [ ] support request

Right now if the file in the ``include`` you are trying to replace contains its own ``include`` statement, the inner ``include`` is not replaced. It would be nice if this could work recursively.

**Comment by bitranox** [comment]
I will look into it - but not any time near. In the meantime You can process the includes manually ... 
yours sincerely
Robert

**Comment by bitranox** [comment]
recursive include statements are supported now.
